### ISSUE TITLE
Broadcast events from actions

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#315]
**Is your feature request related to a problem? Please describe.**

At the moment actions can only return a result to the flow and send logs to its sidecar. It can not publish events back into the system. This would beneficial if you kick-off an action, executes states and wait for an event to come in from that action tp proceed. 

**Describe the solution you'd like**

The action can post cloudevents to the sidecar and it publishes it on that namespace on the actions behalf. With that approach actions can be called async but can be "waited" on later in the workflow.

**Describe alternatives you've considered**

In theory the action could use the GRPC endpoint but it is harder to use and it might be blocked with network policies. It could use the API but for that it would need a secret although the action is already in an authenticated environment. Subflows could be used as well but that means writing "boilerplate workflows" for this use case.

**Comment by alankm** [comment]
The problem you've described is already solvable by wrapping the action in a subflow. 

From the suggestion I take it that the API can be as simple as posting a complete cloudevent. I wonder if it might be more use friendly if we do something a little bit "smarter". Even something small like maybe autogenerating the Cloudevent's "source" field so that global or namespaced functions can be automatically filtered. And perhaps adding an "instance-id" field or similar so that the the waiting instance can avoid conflicting with other instances.

**Comment by jensg-st** [comment]
I think an async subflow would be doing exactly that.
