### ISSUE TITLE
Adding transform to catch

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#342]
**Is your feature request related to a problem? Please describe.**

If I want to have a generic end of a flow, e.g. producing and event it would be nice if the catch could do a transform as well. I could just override a "type" field with the error code and generate an event after that. In this case the success and error condition could transition to the same end state but with different outcome.

```yaml
  catch:
  - error: "*"
    transition: generate-event
    transform: jq(. = { "type":  .error.code } )
```

**Describe alternatives you've considered**

 It could go to a noop now as interim step but that seems to be unnecessary.

**Comment by alankm** [comment]
This was considered during the design of the spec, but decided against. I believe the reason is because `jq` queries are a common cause of errors, and things get strange if the error handler can throw errors.

If you need to transform after catching an error, you can still transition to a noop state with your transform.

**Comment by jensg-st** [comment]
agreed
