### ISSUE TITLE
Creating a new namespace mirror needs to be followed by page refresh.

### ISSUE THREAD

**Issue by alankm** [direktiv/direktiv#657]
I created a new namespace mirror, which worked. But on the UI it didn't automatically move me to the new namespace, nor did the new namespace show up in the namespaces list automatically. I had to press F5 to find it.

**Comment by jalfvort** [comment]
Could not be replicated, this issue was most likely caused by hitting the max limit on non-ssl SSE connections. However when creating a new namespace, there does seem to be a lack of feedback on the explorer nodes. 

Example: If you are on the explorer page with a loaded list of nodes and create a new namespace, the explorer list does not get cleared until the new namespace is loaded. To fix this bad UX, the explorer list will now indicate that it is loading nodes when switching namespace.
