### ISSUE TITLE
Difference between Direktiv and Argo Workflows/Events

### ISSUE THREAD

**Issue by cloudcompute** [direktiv/direktiv#745]
Hi

How do these two differ? Is there any significant benefit that Diretkiv offers than its 'Argo Workflow.Events' counterpart?

PS: I do not know where to post this question. So I am asking here, this is not an ideal place probably.

**Comment by jensg-st** [comment]
We have a slack channel to ask questions but git issues is fine too. Tbh I haven't had a look at Argo events to tell you the difference between our event handling and Argos. The Direktiv design is bound to Knative eventing and Direktiv acts as source and sink for Knative eventing which means it can publish events back to Knative and consume events from Knative as well. Within the engine we are using events as well so a flow can publish messages internally and subflows can consume them. 

When it comes to workflows there are differences but at the end every workflow engine has the same concept of states/tasks and it walks through them, loops, foreach, parallels etc. I think the main difference is the use of Kubernetes. Direktiv is trying to "hide" Kubernetes. Users don't have to know and understand Kubernetes. We don't have CRDs and kubectl is not necessary. That is probably the main difference between the two if you compare Argo with our open source version. In theory we could run on Hashicorp Nomad if we write a new interface for functions which are using Knative at the moment.  

If there are any specific questions please let me know.

**Comment by cloudcompute** [comment]
Hi @jensg-st 

I have understood you, thanks.

There is another question which is not specific to Direktiv, it is about using serverless in Kubernetes. Given the fact that Kubernetes supports HPA scaling, what is the major benefit of introducing Knative Serverless scaling in Kubernetes, I googled but didn't get a  satisfactory answer. 

_Taken from Knative Serving_ It provides automatic scaling for applications to match incoming demand... This is provided by default, by using the Knative Pod Autoscaler (KPA). For example, if an application is receiving no traffic and scale to zero is enabled, Knative Serving scales the application down to zero replicas.

OpenShift and Alibaba say that you can reduce application deployment costs by using Knative but how? But the most popular publich cloud is AWS. The serverless application code is finally run in an EC2 instance.

Does EC2's auto scaling feature has anything to do with K8S's HPA (and/or Knative Serving)? When we configure an EC2 instance, we buy a fixed amount of Memory and CPU for which we have to pay no matter how often we use.

Now if our K8S application (with Knative Serving enabled) is using the EC2 instances under the hood, and assume we do not access the application even once in a month. So we won't be charged anything Or do we need to pay a minimum fee which corresponds to the amount of cpu/memory configured for the EC2 instances with autoscaling enabled Or some other amount?

Also, serverless has cold start issues too.

If you can throw some light on this, it'd be great. Thank you.

**Comment by cloudcompute** [comment]
Hi @jensg-st 

I have understood you, thanks.

There is another question which is not specific to Direktiv, it is about adding the serverless support in Kubernetes. Given the fact that Kubernetes supports HPA scaling, what is the major benefit of introducing Knative Serverless scaling in Kubernetes, I googled but didn't get a  satisfactory answer.

_Taken from Knative Serving_ It provides automatic scaling for applications to match incoming demand... This is provided by default, by using the Knative Pod Autoscaler (KPA). For example, if an application is receiving no traffic and scale to zero is enabled, Knative Serving scales the application down to zero replicas.

When we configure an EC2 instance, we buy a fixed amount of Memory and CPU for which we have to pay no matter how often we use. 

Now if our K8S application (with Knative Serving enabled) is executing the serverless code inside the EC2 instances under the hood, and assume we do not access the application even once in a month for the worker nodes. So we won't be charged anything Or do we need to pay a minimum fee which corresponds to the amount of cpu/memory configured for the EC2 instances with autoscaling enabled Or some other amount?

OpenShift and Alibaba say that you can reduce application deployment costs by using Knative. But I have not come across any such claim made by AWS.

Also, serverless has cold start issues but Kubernetes containers are always warm (always running). While Kubernetes containers have no runtime-based time constraints, serverless functions are set to run for a short duration. Kubernetes favour stateful apps, on the hand serverless functions are stateless. So what made the community to add Knative to Kubernetes, I wonder.

If you can throw some light on this, it'd be great. Thank you.

**Comment by cloudcompute** [comment]
Hi @jensg-st 

I have understood you, thanks. There is another question which is not specific to Direktiv, it is about adding the serverless support in Kubernetes.

_Taken from Knative Serving_ It provides automatic scaling for applications to match incoming demand... This is provided by default, by using the Knative Pod Autoscaler (KPA). For example, if an application is receiving no traffic and scale to zero is enabled, Knative Serving scales the application down to zero replicas.

Given the fact that Kubernetes supports HPA scaling, what is the major benefit of introducing Knative Serverless scaling in Kubernetes. They could have added this functionality to plain HPA itself, instead of adding more complexity to the already-complex Kubernetes.

I have little knowledge about Kubernetes, so this question of mine may sound dull. When we configure an EC2 instance, we buy a fixed amount of memory and cpu for which we have to pay no matter how often we use.

Now if our K8S application (with Knative Serving enabled) is executing the serverless code inside the EC2 instances under the hood, and assume we do not access the application even once in a month. So we won't be charged anything for the worker nodes Or do we need to pay a minimum fee which corresponds to the amount of cpu/memory configured for the EC2 instances with autoscaling enabled Or some other amount?

OpenShift and Alibaba say that you can reduce application deployment costs by using Knative on their cloud. But I have not come across any such claim made by AWS.

Also, serverless has cold start issues but Kubernetes (in theory at least) containers should always be warm (running). While Kubernetes containers have no runtime-based time constraints, serverless functions are intended to run for a short duration. Kubernetes favour stateful apps, on the other hand serverless functions are stateless.

So what made the community to add Knative to Kubernetes, I wonder.

If you can throw some light on this, it'd be great. Thank you.

**Comment by cloudcompute** [comment]
Hi @jensg-st 

I have understood you, thanks. There is another question which is not specific to Direktiv, it is about adding the serverless support to Kubernetes.

OpenShift and Alibaba say that you can reduce application deployment costs by using Knative (Knative Serving scales the application down to zero replicas) on their cloud. How can we reduce such costs on AWS and/or Azure?

**Comment by jensg-st** [comment]
Hi,

Is this a general question if there is money saving with Knative / Serverless or the Alibaba specific reserved instance approach with Knative?

**Comment by jensg-st** [comment]
There are multiple reasons why Knative is a good idea in my opinion. For me one of the main points using Knative is the ease of use if you are in a Kubernetes environment. It is just a almost perfect deployment solution. If you have HTTP based backends it just makes a lot of sense. Instead of having multiple yaml files with deployment, services etc. Knative does it in one simple deployment file. And it comes with additional stuff like revisions, traffic management. If you are unsure, give it a test run and I think Kubernetes deployments getting much easier. You can even avoid cold-starts and start with one pod up all the time. 

Looking at the article which is very shallow I'm assuming it is about the Kubernetes CPU and memory request values. In particular memory. Let's say you have 10 pods with Memory requests of 100MB which means you "block" a GB all the time whereas it is lower in average if you use Knative. That depends on the traffic pattern of course but if you have constant traffic then scaling-to-zero does not add much value anyways. The idea is here (at least I think that is what they mean) that you can heavily oversubscribe CPU and in particular memory. For example we are using Knative services for our functions. You can have hundreds of functions which would eat up a lot of memory / CPU (in terms of Kubernetes `request`) but usually they are not needed at the same time. Therefore you can have 100s of Knative services on a three node cluster. If you add node auto-scaling to the mix I can see cost savings (although the cold-start times are probably insane then). For us it is extremely useful and because our stuff has mostly a workflow character not service orchestration. The cold-start times don't matter too much. It doesn't matter if you flow runs for one minute or one minute and 10 seconds. And for your apps the response times might not matter, e.g. 1 second vs 5 seconds. 

The question was if you save money and resources? I personally think deployments with Knative are easier to manage which is potential time and money saving. This is for me a big win already. The cost savings in terms of resources really depends on your usage/request patterns I reckon. If you are ok with cold-starts for e.g internal apps and have these "spread-out" requests you can oversubscribe the cluster by a lot.

**Comment by cloudcompute** [comment]
Hi

I knew that if we use Knative all we we need to specify is the container name in the function's manifest. The second paragraph really makes sense (something new I have learned) and  the usage patterns (for example amount of traffic we are receiving) can help us choose somewhat-precise amount of resources.

Yes, cold starts is a major issue, end users and stakeholders don't like them. To write serverless functions, I think we should use a language like Rust whose spin up time is a few milliseconds. Java developers should consider using GraalVM (instead of JVM). Its boot time, performance, memory consumption is awesome. Quarkus framework is based on it. 

You might be aware of this Kubernetes auto-scaling component, it could add some value to Directkiv..  
https://keda.sh/docs/2.9/scalers/

I think cloud native concept is really picking up, my guess is that we'd see deployments on bare metals.

Regards

**Comment by jensg-st** [comment]
Hi

we have had a look at keda because we thought we might use it for a more event driven approach for the functions but it was too error prone so we decided against it for now. We build a custom scaler but managing in the backend seemed painful for now and using the HTTP one doesn't add much value because Knative does the same. 

Anyways, I hope this little discussion was helpful for you. It was for me. I'm closing it now and feel free to open a new one or use Slack. Up to you.
