### ISSUE TITLE
Register for Slack: Need @direktiv.io or @iqconsult.com.au email

### ISSUE THREAD

**Issue by agardnerIT** [direktiv/direktiv#856]
<img width="528" alt="Screenshot 2023-04-29 at 8 47 47 pm" src="https://user-images.githubusercontent.com/26523841/235298793-8efa7d5f-b0a3-4ad7-b96e-c6e82f41ee61.png">

I'm trying to join your Slack but I can't as I need an invite.

You could generate an invite then use that hyperlink on the website rather than a direct link?

**Comment by wwonigkeit** [comment]
Hi Adam, what link did you use? I tested the link from the GitHub page below with a new test account  and it worked fine?

https://join.slack.com/t/direktiv-io/shared_invite/zt-zf7gmfaa-rYxxBiB9RpuRGMuIasNO~g

This is the open-source invite and anyone can join. Let me know what link you used so that I can remove it please.

**Comment by agardnerIT** [comment]
I followed the footer link on https://docs.direktiv.io

**Comment by wwonigkeit** [comment]
Thanks I'll get that updated!!
